services:
  web:
    build: .
    container_name: TaskTrackerWeb
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/tasktrackerdatabase
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: tasktracker_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: tasktrackerdatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: